# .github/workflows/changesets-pr.yml
name: Changesets Version PR

on:
  push:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  version-pr:
    if: github.repository == 'thuvaragan-dm/dm-desktop-test'
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        # Runs 'npm ci' at the root of your repository, as package.json is at the root
        run: npm ci

      - name: Create or Update Version PR
        id: changesets-pr
        uses: changesets/action@v1
        with:
          # This command runs the 'version-script' from your root package.json.
          version: npm run version-script
          title: "chore: Upcoming Release Version Bump"
          commit: "chore: update version and changelog via Changesets"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
