# .github/workflows/release-electron-app.yml
name: Build and Release Electron App

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        # Runs 'npm ci' at the root of your repository
        run: npm ci

      - name: Build and Package Electron App
        # This command runs your 'build' script (defined in your root package.json)
        # which should execute 'tsc && vite build && electron-builder'.
        # The '--publish onTagOrCreate' flag tells electron-builder to publish a release
        # if the current commit is tagged.
        run: npm run build -- --publish onTagOrCreate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # --- Windows Code Signing Example (set secrets in GitHub repo settings) ---
          # CSC_LINK: ${{ secrets.WINDOWS_PFX_BASE64 }}
          # CSC_KEY_PASSWORD: ${{ secrets.WINDOWS_PFX_PASSWORD }}

          # --- macOS Code Signing & Notarization Example (set secrets) ---
          # APPLE_ID: ${{ secrets.APPLE_ID_EMAIL }}
          # APPLE_ID_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          # APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          # APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
          # APPLE_API_ISSUER_ID: ${{ secrets.APPLE_API_ISSUER_ID }}
          # APPLE_API_KEY_CONTENT: ${{ secrets.APPLE_API_KEY_P8_BASE64 }}
