name: Build and Release Electron App

on:
  push:
    tags:
      - "v*.*.*" # Trigger this workflow when a tag like v1.0.0, v0.1.2, etc., is pushed

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Use the Node.js version from your root package.json

      - name: Install Dependencies
        # Runs 'npm ci' at the root of your repository
        run: npm ci

      - name: Build and Package Electron App
        # Changed --publish onTagOrCreate to --publish onTag
        run: npm run build -- --publish onTag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # --- Windows Code Signing Example (set secrets in GitHub repo settings) ---
          # CSC_LINK: ${{ secrets.WINDOWS_PFX_BASE64 }}
          # CSC_KEY_PASSWORD: ${{ secrets.WINDOWS_PFX_PASSWORD }}

          # --- macOS Code Signing & Notarization Example (set secrets) ---
          # APPLE_ID: ${{ secrets.APPLE_ID_EMAIL }}
          # APPLE_ID_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          # APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          # APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
          # APPLE_API_ISSUER_ID: ${{ secrets.APPLE_API_ISSUER_ID }}
          # APPLE_API_KEY_CONTENT: ${{ secrets.APPLE_API_KEY_P8_BASE64 }}
